# Generated by Django 5.1.4 on 2025-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=20)),
                ('PHONE', models.IntegerField()),
                ('EMAIL', models.CharField(max_length=20)),
                ('USERNAME', models.CharField(max_length=20)),
                ('PASSWORD', models.CharField(max_length=20)),
            ],
        ),
    ]
